import "./globals.css";
import type { Metadata } from "next";
import TopNav from "@/components/TopNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col w-full bg-[#f6f6f6]" id="main">
          <TopNav />
          <div className="flex w-full h-full bg-[#f6f6f6]">{children}</div>
        </div>
      </body>
    </html>
  );
}
