import Navs from "@/components/SideBar";
import "./globals.css";
import type { Metadata } from "next";
import SideBar from "@/components/SideBar";
import TopNav from "@/components/TopNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="flex flex-row w-full bg-[#f6f6f6] id='page">
        <SideBar />
        <div className="flex flex-col w-full" id="main">
          <TopNav />
          <div className="flex w-full h-full bg-[#f6f6f6]">{children}</div>
        </div>
      </div>
    </html>
  );
}
